name: Docker de Frontend en Producción

# Controlar cuando se va a ejecutar esta action
on:
  # Decimos que se va activar en el "push" a la "branch" de "main".
  push:
    branches: 'main'

  # También podemos correr manualmente la action
  workflow_dispatch:

# Ahora las tareas a realizar
jobs:
  # Sólo vamos a hacer la tarea de hacer el build de la image de docker
  build:
    # El runner es el sistema operativo a usar, usaremos ubuntu
    runs-on: ubuntu-latest

    # Pasos a realizar
    steps:
      # Cambiarse a la rama main
      -
        name: Checkout 
        uses: actions/checkout@v2
      # Hacer login en DockerHub
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Establecer el programa que va hacer el build de la image
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Hacer el build y publicarlo en DockerHub
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/encuestas-uam-front:latest
