version: '3.9'
services:
  sv-apache:
    image: httpd
    networks:
      - frontal
    ports:
    - "80:80"
  
  sv-tomcat:
    image: tomcat
    networks:
      - frontal
      - middleware
    ports:
    - 8080:8080

networks:
  frontal:
  middleware: 
